apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: mcp-stateful-app

build:
  artifacts:
    - image: myfastapimcp/stateful-app-api
      context: app
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    sha256: {}

deploy:
  helm:
    releases:
      - name: mcp-stateful-app
        chartPath: charts/mcp-stateful-app/
        valuesFiles:
          - charts/mcp-stateful-app/values.yaml
        namespace: mcp-stateful-app
