{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis.fullname" . }}-master
  labels:
    app: {{ include "redis.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "redis.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "redis.fullname" . }}
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: "{{ .Values.redis.image.pullPolicy }}"
          ports:
            - name: redis
              containerPort: {{ .Values.redis.port }}
          resources:
{{ toYaml .Values.redis.resources | indent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}-master
  labels:
    app: {{ include "redis.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: {{ .Values.redis.port }}
      targetPort: redis
  selector:
    app: {{ include "redis.fullname" . }}
{{- end }}