replicaCount: 3

image:
  repository: myfastapimcp/stateful-app-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

persistence:
  enabled: true
  storageClass: standard
  accessMode: ReadWriteOnce
  size: 1Gi

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

nginx:
  enabled: true
  replicaCount: 2
  fastapiReplicas: 3
  image:
    repository: openresty/openresty
    tag: alpine
    pullPolicy: IfNotPresent
  service:
    port: 80
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

redis:
  enabled: true
  port: 6379
  image:
    repository: "redis"
    tag: "6.2-alpine"
    pullPolicy: "IfNotPresent"
  resources: {}